### ISSUE TITLE
Center page title

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#100]
The page icon/title should be centered - on Android it is currently left aligned (works fine on iOS)

![Screenshot_20191217-164612_Expo](https://user-images.githubusercontent.com/8822863/71018694-3ff22200-20f9-11ea-85d6-9864fe5c0f08.jpg)

**Comment by nlkassad** [comment]
when this is being reviewed, it's worth reviewing the other alignment of text items on this page.
It looks like the text in the trash item buttons may be aligned towards the top.
