### ISSUE TITLE
Move the 'Share in local feed" toggle. 

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#103]
Remove the 'Share to local feed' toggle from login page (we'll add it to profile once we have one)
Add it to the bottom of the plog page, right below the Plog button:

Update label to: "Share in Local feed" (on by default, but remember the last user choice).
Exactly like  https://marvelapp.com/96b0bd4/screen/53564903

![IMG_5224](https://user-images.githubusercontent.com/8822863/71019951-9bbdaa80-20fb-11ea-8c17-0e282776b13d.jpg)

**Comment by nlkassad** [comment]
add the toggle back here and remove from the profile screen
