### ISSUE TITLE
iOS - remember data by default

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#105]
- When I reload the iOS app in Expo, it goes back to the tutorial, and does not remember what I did
- Android does remember my data (even though I didn't create an account)

**Comment by nlkassad** [comment]
We need to confirm that it's saving the user information in iOS.
In my testing, I could not confirm in expo. 
This should also be tested on a live device to confirm behavior.

**Comment by kaniasty** [comment]
Works in Simulator - need to re-test pre-deployment.
