### ISSUE TITLE
Plog Badges

### ISSUE THREAD

**Issue by nlkassad** [codeforboston/plogalong#11]
https://marvelapp.com/96b0bd4/screen/53618667
As user achieves badges, they turn from b&w to color.
Clicking on an achieved badge brings up the achievement unlocked modal - https://marvelapp.com/96b0bd4/screen/45978632
For MVP, grayed out badges are not clickable

**Comment by kaniasty** [comment]
Badge info and badge images are stored here, but should eventually be moved into Firebase.
https://airtable.com/shr3Kqv6dNrkz2xe9
