### ISSUE TITLE
Create account screen - password field

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#117]
Password fields need to be masked ****

Bonus for including little 'eye' toggle to show/hide it.

**Comment by zachjohnston** [comment]
This looks like it has been resolved in iOS (see below).  @kaniasty, did you see this on iOS or Android?

<img width="370" alt="image" src="https://user-images.githubusercontent.com/5273704/73353026-78406080-4260-11ea-8b6f-bb0045b0d33b.png">
