### ISSUE TITLE
Launch iOS alpha

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#126]
Launch app for internal testing

Ben - I invited you to the account. You'll need to accept the invite - if anyone else needs to be added, please dm me the email address I should use. 

Step 1 - help Eva configure the app - at Hack Night (https://www.dropbox.com/s/xlupd2l06wxp93n/Certificates%2C%20Identifiers%20%26%20Profiles%20-%20Apple%20Developer.pdf?dl=0)

Step 2 - launch app for internal testing

Step 3 - add test users (enter apple IDs)

**Comment by kaniasty** [comment]
I'm trying to take screenshots for the Apple store, but for whatever reason the resolution is too low... might have to take them using the simulator. 
For  6.5 inch we need 1242 x 2688
For 5.5 inch we need 1242 x 2208

**Comment by zachjohnston** [comment]
We did it! 🎉
