### ISSUE TITLE
Clear "email already is use" error

### ISSUE THREAD

**Issue by zachjohnston** [codeforboston/plogalong#131]
If a user tries to create another account with an email already in use, they see a red error message:

<img width="377" alt="Screen Shot 2020-02-16 at 1 59 40 PM" src="https://user-images.githubusercontent.com/5273704/74610830-ba70fb00-50c4-11ea-8512-fb0123d63bef.png"> 

If the user closes the modal (tap X) and re-opens it, the message is still there:

<img width="370" alt="Screen Shot 2020-02-16 at 1 59 58 PM" src="https://user-images.githubusercontent.com/5273704/74610932-a974b980-50c5-11ea-8ef6-16208fa50189.png">

This message should be cleared if the user closes the modal.

**Comment by kaniasty** [comment]
Add "Please log in." to the end of the error message. 

- clear the password field
- Hide the Retype password field
- Change button to Login instead of register, and include Forgot password field (#162)
