### ISSUE TITLE
More>Contact Us

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#134]
Page Title: Contact Us (insert below FAQ)

Topic (dropdown): Feedback / Comment / Bug / Other
Comment: (text area - 5 lines)
Name (optional): (input)
Email (optional): (input)
Submit (button)

**Comment by bighappytrees** [comment]
@zachjohnston @bdougsand 
How do we feel about using react-native-clean-form for this? https://github.com/esbenp/react-native-clean-form

**Comment by bdougsand** [comment]
Closed by @k-charette in PR #184

**Comment by kaniasty** [comment]
The submit button does not work.
