### ISSUE TITLE
Logged in Profile page - streamline for MVP

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#139]
Make the following changes:

- Enlarge the photo and center it horizontally above other content
- Center 'Personal Account' under the photo
- Hide badges box
- Delete the 'Hello, username!' line
- Make email address editable - see  https://marvelapp.com/96b0bd4/screen/53525464

**Comment by zachjohnston** [comment]
Allowing users to change their email address will require some firebase work.  Opened new issue #194 for that.
