### ISSUE TITLE
Use profile photo in plog log

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#143]
If a user has set a profile picture, show it as part of their plogs.

**Comment by bdougsand** [comment]
Closed in commits 7a391ed46a4662a955a26d013a67818c6b142a2b and 37d0026a30b4c99be77d057ba72b241b361ee924

**Comment by kaniasty** [comment]
Once user adds a profile picture (and username), that profile/username shows up in their history going forward.  However, it does not update the plog history (I think?).  At the moment, there seems to be a History bug where Local is shown, but history is blank.
