### ISSUE TITLE
Add temperature and weather icon to PlogScreenWeather

### ISSUE THREAD

**Issue by bdougsand** [codeforboston/plogalong#147]
**Describe the solution you'd like**
Try to match the MVP:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/10840531/75916318-232ad800-5e26-11ea-9465-56f8290e1b67.png">

**Comment by ValerieKenyon** [comment]
I'd like to work on this one.

**Comment by bdougsand** [comment]
Closed by @ValerieKenyon in PR #169
