### ISSUE TITLE
Plog History - All

### ISSUE THREAD

**Issue by nlkassad** [codeforboston/plogalong#17]
This is the Plog Log on the Local screen.
By default, it should show the 5 most recent, closest plogs, then infinite scroll into 5 more, etc.  Blank slate will show if there is no other plogs within 5 miles of the user's current location. 
https://marvelapp.com/96b0bd4/screen/45305403

**Comment by ps37** [comment]
Can you please add more description about this task?

**Comment by kaniasty** [comment]
This is the 'Local' tab, which shows history for everyone, not just the user themselves.  Same data as history, just filtered differently.

**Comment by nlkassad** [comment]
geofire - query by region
