### ISSUE TITLE
Random content and style updates

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#201]
Plog:

- [x] Center camera icons horizonally and vertically within their green boxes

History:

- [x] Yellow block: Change "You plogged for # minutes this year." to "You earned # plogging minutes this year. "

- [x] Achievement: Change +# bonus minutes to "+# minutes"

Local:

- [x]  Either remove yellow block, or update to be dynamic: 

- [x]  "There are # ploggers nearby."  (count all ploggers who plogged nearby in the last month)

- [x] "There are no other ploggers nearby.  Start a trend!"

Profile (new account created):

- [x] Fix formatting - center photo placeholder 
- [x] Remove extra vertical white space

![IMG_6839](https://user-images.githubusercontent.com/8822863/81130094-83b4bf00-8f14-11ea-8fac-7a6dbab1ad13.JPG)

Profile (no account created):

Simplify button labels:
- [x] Create Account
- [x] Log In

- [x] Put the photo placeholder above buttons
- [x] Add 'Mysterious Plogger' label below the photo (instead of Personal Account/Email) 
(this section should look the same as the top of the new profile page once an account is created that was fixed above) 

More>About 

- [x] Remove the teal background from text blocks.
- [x] Use standard button style, and have it say "Visit plogalong.com" 

All the More> subsections

- [x] Update the back arrow treatment with an SVG as shown below:

https://marvelapp.com/96b0bd4/screen/53564657

**Comment by ValerieKenyon** [comment]
More > AboutScreen, link button to "Visit plogalong.com" 
and 
HistoryScreen Banner, duplicate instance of "minutes" 
are fixed by PR #227

**Comment by ValerieKenyon** [comment]
I think Profile > Create Account and Login buttons have been fixed.
I've added a commit that comments out the second instance of the Logout button on ProfileScreen.
