### ISSUE TITLE
Plog Log Form - Change map location

### ISSUE THREAD

**Issue by nlkassad** [codeforboston/plogalong#21]
https://marvelapp.com/96b0bd4/screen/53564903
Ideally, the user should be able to drag/drop the detected location.
For MVP, users MUST agree to share location to use the app.  If user has chosen not to share location, pop up location sharing when they hit the plog page. 

Re: privacy:
Share plog data/location 5 minutes after user submits their plog. User can choose not to share their plog in the local feed or facebook, therefore protecting their privacy.

**Comment by bdougsand** [comment]
I think this has been superseded by #175
