### ISSUE TITLE
Plog Log Form

### ISSUE THREAD

**Issue by nlkassad** [codeforboston/plogalong#22]
Short Description

Link to related wireframe page
https://marvelapp.com/96b0bd4/screen/53564903

Related Screen(s) and dependent screens

Tasks
- 
- 

Tests (acceptance requirements)

- 
-

Related Issues

Comments

**Comment by kaniasty** [comment]
FYI - we are cutting the 'Flag' function from v. 1 due to confusion during user research.  It also doesn't make that much sense unless/until it's integrated with city services.
