### ISSUE TITLE
More about - add links

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#222]
There are some links in that content that need to actually be added. :)

Paragraphs 3 and 4

**Comment by kaniasty** [comment]
@ValerieKenyon 99% done - the lik to slipper studios has to be http://slipperstudios.com, not https, as there is no https.

**Comment by ValerieKenyon** [comment]
I've fixed the http link.  It's in a branch that I've made to tweak a couple of small things that I've noticed.
