### ISSUE TITLE
Modal Overlays

### ISSUE THREAD

**Issue by bdougsand** [codeforboston/plogalong#25]
Several views—the introductory screens, alerts, terms and conditions, and invite dialog—share the same overlay style:

<img width="150" alt="Screen Shot 2019-04-08 at 5 46 55 PM" src="https://user-images.githubusercontent.com/10840531/55759305-fc51ff00-5a26-11e9-9de0-d4bf8f897f54.png"><img width="150" alt="Screen Shot 2019-04-08 at 5 50 59 PM" src="https://user-images.githubusercontent.com/10840531/55759306-fc51ff00-5a26-11e9-92f8-103c8381ac63.png"><img width="150" alt="Screen Shot 2019-04-08 at 5 47 34 PM" src="https://user-images.githubusercontent.com/10840531/55759307-fc51ff00-5a26-11e9-87b5-f18299d638ba.png">

They cover other views, are dismissed through user action, and don't stack.

**Comment by ValerieKenyon** [comment]
I don't understand exactly what you mean by "don't stack" - do you mean that if one of them is showing but then is closed, it goes back to the previously viewed screen?
