### ISSUE TITLE
Revise achievement icons

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#254]
See the flagged items in https://airtable.com/shrHq1EmZzFO7hiQe

Some icons have to be updated to make sure we have a license to use them.

**Comment by kaniasty** [comment]
Update the last 8 icons in this list:

https://airtable.com/shr3Kqv6dNrkz2xe9

**Comment by ValerieKenyon** [comment]
These are all from Google and are considered open-source.  Here is the license information: https://www.apache.org/licenses/LICENSE-2.0.html

**Comment by nlkassad** [comment]
'update icon' or have a link to an icon.

- [x ] True Native
- [ ] Bug Zapper - selected icon needs attribution
- [x ] Team Effort
- [ ] Dog Days - selected icon needs attribution
- [ ] Spring Chicken - selected icon needs attribution
- [x ] Fall Color
- [ ] Polar Bear - selected icon needs attribution
- [ x] Break the Seal

Need confirmation on what we should be using as a resource and if we should use flat icon svgs with special attribution.
Material icons seem not to have the same requirement.
