### ISSUE TITLE
Intro Screens: Layout

### ISSUE THREAD

**Issue by bdougsand** [codeforboston/plogalong#28]
Lay out the contents of the intro pages:

https://marvelapp.com/96b0bd4/screen/53525464
https://marvelapp.com/96b0bd4/screen/45978808
https://marvelapp.com/96b0bd4/screen/45978980
https://marvelapp.com/96b0bd4/screen/46027468

Implement swipe/click behavior

**Comment by kaniasty** [comment]
![Plogalong-Spec (dragged)](https://user-images.githubusercontent.com/8822863/62323085-7f82df00-b474-11e9-9ff5-d32c28d8dfda.png)
