### ISSUE TITLE
Can't exit camera once selected

### ISSUE THREAD

**Issue by nlkassad** [codeforboston/plogalong#29]
![Screen Shot 2019-05-07 at 7 42 07 PM](https://user-images.githubusercontent.com/3656039/57339665-83ff5c00-7100-11e9-9dbc-51a74b80fc8a.png)

**Comment by zachjohnston** [comment]
Fixed on iOS, can we close this?

![IMG_FBB28E8D405C-1](https://user-images.githubusercontent.com/5273704/73510853-98336980-43b1-11ea-95fe-87f13e045944.jpeg)
