### ISSUE TITLE
Display current weather on Plog Screen

### ISSUE THREAD

**Issue by bdougsand** [codeforboston/plogalong#30]
<img width="344" alt="Screen Shot 2019-05-07 at 9 48 04 PM" src="https://user-images.githubusercontent.com/10840531/57343546-c4b3a100-7111-11e9-9be4-d0bbb7347ed2.png">

**Comment by ValerieKenyon** [comment]
I'm interested in working on this (but I'm not very confident about it).  I'm thinking to do these 2 main things:
1. figure out how to let the app access location
2. use that information as an input in a function to access the appropriate weather data.
I'll keep a separate record of what I find/figure out.

**Comment by ValerieKenyon** [comment]
Here's some starter pseudo-code.

`import React from "react"

function FindLocation() {
	if (navigator.geolocation) {
		return navigator.geolocation.getCurrentPosition()
	}
}

export default FindLocation



————————————————————————
// or possibly combine these into one component?
————————————————————————



import React from "react"
import FindLocation from "./FindLocation.js"

function WhatsTheWeather() {

// put FindLocation info into api.weather.gov or into a function that accesses it
// return a short friendly statement about conditions for plogging

}

export default WhatsTheWeather`

Any thoughts/feedback would be appreciated!
