### ISSUE TITLE
Profile image uploader distorts the image if it doesn't match dimensions.

### ISSUE THREAD

**Issue by nlkassad** [codeforboston/plogalong#300]
**Describe the bug**
From testflight - My profile picture is smushed horizontally making my face look strange.
https://appstoreconnect.apple.com/apps/1497818996/testflight/screenshots/APSf7mfNB3rsVcwF9KA4cdQ?preReleaseVersionId=633c6913-760e-4935-ab96-ca57a6432edd&sort=-timestamp

**To Reproduce**
1. Go to 'profile page'
2. Click on 'profile image icon' to upload image
3. Image will resize to set ratio

**Expected behavior**

**Screenshots**
![original](https://user-images.githubusercontent.com/3656039/104396483-be95da80-5518-11eb-92b1-1afad2d277c0.jpg)

**Additional context**

**Comment by bdougsand** [comment]
Fixed in 524fa0005a1011918ea2add1d9b18bccebd59c16
