### ISSUE TITLE
Fix Android store issues

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#308]
The google Pre-launch report lists a number of issues for us to fix before we can release.

**Comment by nlkassad** [comment]
Looks like it's this
https://play.google.com/console/u/0/developers/7766193917348219728/app/4975099663974754242/pre-launch-report/overview
Most likely the error that's blocking
<img width="958" alt="Screen Shot 2021-02-16 at 9 04 00 PM" src="https://user-images.githubusercontent.com/3656039/108146107-9a3e9800-709a-11eb-83de-bcba5cc76f45.png">
May be related to the way that it's being checked
https://stackoverflow.com/questions/64706041/fatal-exception-firebase-messaging-intent-handle-java-lang-noclassdeffounder

**Comment by ShepherdBook** [comment]
Pre-launch report warning:

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at b.g.m.t.l(ViewCompat.java:4)
	at b.g.m.t.k(ViewCompat.java:3)
	at b.g.m.t.J(ViewCompat.java:1)
	at com.facebook.react.uimanager.Rea
