### ISSUE TITLE
Consider privacy implications of design

### ISSUE THREAD

**Issue by bdougsand** [codeforboston/plogalong#33]
- User name visibility
- Location visibility and granularity -- can we avoid storing precise location data entirely?
    - Uses of location: "hyper-local" specials, aggregate
- Think about ethics so that the engineers don't have to! (That was a joke.)

**Comment by kaniasty** [comment]
This is rough strategy for Phase I:

- Username/photo on profile are optional, or can be anonymized as the user sees fit.
- Share plog data/location 5 minutes after user submits their plog (ideally, user should be able to drag/drop exact location). User can choose not to share their plog in the local feed or facebook, therefore protecting their privacy. 
- I'll think about ethics at some point...
