### ISSUE TITLE
Populate content for More>About Plogalong

### ISSUE THREAD

**Issue by bdougsand** [codeforboston/plogalong#35]

**Comment by kaniasty** [comment]
Content draft is here:

https://docs.google.com/document/d/1a5ug5QYviodWcW3h3tiAbu8WAWX4IygXeT0f3DppuVk/edit#heading=h.elma1wgkht8e

**Comment by kaniasty** [comment]
Remove the purple background from this section. 

**About Plogalong**

When you plog, you pick up trash as you go about your daily life... jogging, hiking, or simply walking down the street. Ploggers help keep our neighborhoods, parks, and oceans clean.

Plogalong helps you track your plogging history and see who else is plogging nearby. Stay motivated by earning badges and plogging minutes, or sharing your plogs on social media.

Plogalong was designed by Slipper Studios (link to slipperstudios.com), and was built as an open source civic project at Code for Boston (link to C4B).

Plogalong.com (button)
