### ISSUE TITLE
Plog data into Firebase

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#37]
I generated some test content, plus tables of data for form elements that can be sorted by ID.
I included a toggle for each item so that it can be shown or hidden as needed).

https://www.dropbox.com/sh/msmb6vn8h8x4uqi/AACuGRYDQ1QODdxtsfPb9c8ja?dl=0

Stay tuned for more data re: achievements etc.

**Comment by kaniasty** [comment]
After doing some research, I believe that you can't import from Json into the Firestore using the UI, but you can do it programmatically.  Please see my notes about Firebase/Airtable access in Slack.

https://levelup.gitconnected.com/firebase-import-json-to-firestore-ed6a4adc2b57

**Comment by kaniasty** [comment]
Database schema is here:
https://www.dropbox.com/s/9trcuuu8oqzlapc/PlogalongDB.pdf?dl=0

Sample content for some tables is here:
https://airtable.com/shrHq1EmZzFO7hiQe

**Comment by nlkassad** [comment]
JSON can be imported into Firebase, there may be some complications with geofirestore.
Marking this as done for now, we can reopen later as needed.
