### ISSUE TITLE
Issue Template (Copy when creating a new issue!)

### ISSUE THREAD

**Issue by nlkassad** [codeforboston/plogalong#46]
Short Description

Link to related wireframe page
https://marvelapp.com/96b0bd4/screen/53564903

Related Screen(s) and dependent screens

Tasks (to complete this issue)

- 
- 

Logic/UI Behavior

- 
- 

Tests (acceptance requirements)

- 
-

Related Issues

- 
-

Related User Research/Usability Test Findings

- 
-

Comments

- 
-

**Comment by bdougsand** [comment]
Replaced by template by @nlkassad in 7ffb4c65
