### ISSUE TITLE
Implement 'filmstrip' UI

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#60]
Outstanding Tweak:

- [ ] Hide the horizontal scroll bar that appears when user swipes across achievements. 

A filmstrip is a row of photos or icons that are arranged horizontally and can be swiped through.  There are two instances of film strip in the app:

- on the plog form, the activities the user is doing while plogging don't fit within the horizontal viewport on smaller screens.  If this happens, user should be able to swipe to the remaining icons.   
https://marvelapp.com/96b0bd4/screen/53564903 
https://marvelapp.com/96b0bd4/screen/61131926

- On the History screen, as soon as the user has several achievements, they will no longer fit in viewport. https://marvelapp.com/96b0bd4/screen/45307708

important: to provide affordance (a hint that it's swipable), one icon/element should always show partially on the right side of the screen.  Otherwise the user will not realize that they can interact with the film strip.

**Comment by bdougsand** [comment]
Fixed by @ValerieKenyon in PR #187
