### ISSUE TITLE
Give more priority to photos

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#65]
- [x] - **Move the photo area up, right below the map**
- [x] - **Reduce size of camera icons slightly, while keeping the green outline the same size (the icons are just a bit too large relative to the other icons on the page**

- [x] - Increase the size of the thumbnails so that the width fits the horizontal viewport with a bit of padding in between. Right now the thumbnails are static and too small.

- [x] - Change behavior so that whichever 'camera icon' the user clicks, the photo is loaded into the next available box... If I load a first photo, it is always loaded into the first thumbnail, second photo into second, etc. 

https://marvelapp.com/96b0bd4/screen/61131926

**Comment by nlkassad** [comment]
For clarification this is in regards to thumbnails of photos on the plogging screen
![Screen Shot 2020-01-21 at 6 51 10 PM](https://user-images.githubusercontent.com/3656039/72853350-1fc8fc00-3c7f-11ea-94bf-69d8a94b671f.png)

**Comment by zachjohnston** [comment]
@swmckenna Do you want to take this one?  I remember you were looking at it.

**Comment by kaniasty** [comment]
Looks like this is now working correctly.

Small tweak (@swmckenna)  - can we reduce the size of the camera icons a bit? (Leave the green outline the same, just reduce the camera icons - they're looking kind of big now relative to the people icons below).

**Comment by bdougsand** [comment]
PR #189 moved the photo strip up, so now we just need to fix the icon size to close this issue.
