### ISSUE TITLE
Photo Spec

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#71]
Link to related wireframe pages
Plog: https://marvelapp.com/96b0bd4/screen/53564903
History: https://marvelapp.com/96b0bd4/screen/45307708
Local: https://marvelapp.com/96b0bd4/screen/45305403

Related Screen(s) and dependent screens
Sample photos of trash:
https://www.dropbox.com/sh/u2107zazyv2sdft/AADJYZCinq1jQxN3lW8U132-a?dl=0

Tasks (to complete this issue)
- (complete) When user uploads or takes a photo, show in a square 'mask'; allow user to drag photo within the mask (like Instagram, but don't allow anything other than square format)
- (?)On the back end, crop and reduce file size to a 'reasonable' file size
- (?) Constrain Firebase to only accept photos of a maximum file size
-  (Eva) Include note in terms and conditions re: taking photos of people, ownership of photos, etc.
- (?) On the Plog form, photos should be saved locally even if user closes the app (to allow for taking photos as you plog)
- (incomplete) Allow users to click thumbnails and have them open in a modal; modal is not prototyped, but should look like other modals (https://marvelapp.com/96b0bd4/screen/45440813) , with X in upper right.  Buttons below photo should be as follows: Close and Report Photo buttons on Local page | Close and Remove Photo button on Plog form or History; 
- (complete) Photo should be centered vertically within the modal
- (incomplete) For MVP, Report photo button should flag photo in firebase, hide it from view automatically, and send an email to report@plogalong.com

Tests (acceptance requirements)

- User can take/upload up to 5 photos (complete)
- Photos show/are stored in a square format (complete)
- User can enlarge their own or others' photos (incomplete)
- User can report a photo in the Local feed (incomplete)
- User can remove a photo loaded into the Plog form or History (incomplete)

Related Issues
- https://github.com/codeforboston/plogalong/issues/65 (open)
- https://github.com/codeforboston/plogalong/pull/49 (needs QA)
- https://github.com/codeforboston/plogalong/issues/48 (closed)
- https://github.com/codeforboston/plogalong/issues/83 (open)

Related User Research/Usability Test Findings

- Photo upload design was intuitive to participants
- Some were more interested/focused on photos than completing other information about their plog

Comments

- 
-

**Comment by nlkassad** [comment]
These are all needed but may not be requirements for mvp
