### ISSUE TITLE
Bottom of button is cut off

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#81]
Tested on Galaxy A6 
![Screenshot_20191209-182910_Expo](https://user-images.githubusercontent.com/8822863/70460800-74415f00-1ab7-11ea-9bf8-27f5852a7452.jpg)

**Comment by zachjohnston** [comment]
Also present on iPhone 8:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/5273704/73353882-6069dc00-4262-11ea-8be3-005549777f42.png">

**Comment by kaniasty** [comment]
I thought this was fixed, but I still see it on Android. 
Tested on Samsung Galaxy J1 Ace (SM-J110)
