### ISSUE TITLE
Timer issue on Android

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#82]
Two issues - 

1) I'm seeing multiple alerts (see screenshot). 
2) The issues itself seems to have some workarounds - not sure which one makes the most sense: https://github.com/facebook/react-native/issues/12981

![Screenshot_20191209-183608_Expo](https://user-images.githubusercontent.com/8822863/71014256-f2be8200-20f1-11ea-95df-081a7f96b8be.jpg)

**Comment by nlkassad** [comment]
Fix for this may be stopping timer and resuming when app is brought to the front.
confirmation on the solution is needed.

**Comment by bdougsand** [comment]
Fixed by @mohinderps in PR #156
