### ISSUE TITLE
Camera UI

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#83]
Ideally, this would just use the iOS photo workflow. 

Currently we have the following issues:

- There is no way to exit camera without taking photo
- No way to take horizontal photo
- 'Take photo' button is too narrow vertically - if we are using a non-native function, the button should look like 'Plog' or other larger buttons we use throughout app.

Close related issue:
https://github.com/codeforboston/plogalong/issues/83#issue-535122231

**Comment by nlkassad** [comment]
For MVP we may not need to have it match native ios but the issues mentioned should be resolved
![Screen Shot 2020-01-21 at 6 44 42 PM](https://user-images.githubusercontent.com/3656039/72853030-420e4a00-3c7e-11ea-86b9-f57678b76140.png)
