### ISSUE TITLE
Cleaned up '____'

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#85]
When user does not select a trash type and hits plog, record 'trash' as a default instead of having a blank. 

Right now it says "Cleaned up ."  on the History page
Should say "Cleaned up trash."

**Comment by nlkassad** [comment]
Confirmed issue
![Screen Shot 2020-01-21 at 6 43 08 PM](https://user-images.githubusercontent.com/3656039/72852881-e93eb180-3c7d-11ea-9250-029dfda3c02d.png)
