### ISSUE TITLE
Hiking icon should be purple

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#86]
When user is hiking while plogging, on the History page their icon shows up in black, while rest are purple.

Turn hiking purple.

**Comment by nlkassad** [comment]
Confirmed the issue
![Screen Shot 2019-11-12 at 7 31 46 PM](https://user-images.githubusercontent.com/3656039/72852779-9f55cb80-3c7d-11ea-892d-d5608562ee3b.png)

**Comment by nlkassad** [comment]
constants/color is where it should be retrieving the active color
Issue was occurring because we were specifying the color in the svg
