### ISSUE TITLE
Replace nav with svgs

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#87]
Replace nav icons with the following:
https://www.dropbox.com/sh/wrzsq7mntxsny87/AAAW9XL4kVdP_Jf8HbTx-SOua/nav?dl=0

Use purple as selected state, i.e. if I'm on the history page, history icon should be purple

Close related issue - selected state

https://github.com/codeforboston/plogalong/issues/61

**Comment by nlkassad** [comment]
Can answer questions if this needs clarification

**Comment by kaniasty** [comment]
https://github.com/codeforboston/plogalong/pull/112
