### ISSUE TITLE
Invite screen

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#89]
Implement social share buttons on More>Invite

https://www.npmjs.com/package/react-share

**Comment by nlkassad** [comment]
Might want to remove this from mvp

**Comment by zachjohnston** [comment]
Duplicate of #15

**Comment by kaniasty** [comment]
on IOS, the Share on Facebook, I get the error below.  Other buttons do nothing. 

![IMG_5478](https://user-images.githubusercontent.com/8822863/74791846-9ca0c300-5289-11ea-915c-ad1d1d410d48.PNG)

**Comment by zachjohnston** [comment]
@kaniasty, I updated #15 with your screenshot, so I am re-closing this issue.
