### ISSUE TITLE
Current location map wrong

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#97]
Even though I am not in Boston and have enabled location sharing, I see a map of Boston on the Plog screen.  Once I hit Plog, the map on the history page is correct (recording Poland).

This bug is on Android only - works fine in iOS. 

![Screenshot_20191217-164612_Expo#1](https://user-images.githubusercontent.com/8822863/71012012-b0e00c80-20ee-11ea-91cc-874ca2c1af8b.jpg)

**Comment by nlkassad** [comment]
Need to confirm that we're capturing the current location and displaying it as expected. sometimes with the simulator it's just using a default setting.
