### ISSUE TITLE
You plogged < > 

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#98]
For MVP, forget the place name (i.e. beach).  We'll need it for some achievements later, but let's do this instead for now. 

- If user set a timer> "You plogged for X minutes on DD/MM/YY."
- If user did not set a timer>  "You plogged on DD/MM/YY."

**Comment by nlkassad** [comment]
For context we don't need to remove that from logging, but if it's not displaying how we want we can just log the date or date + time as mentioned.

**Comment by kaniasty** [comment]
I am being told that I plogged for 13 hours, when it's been less than a minute.
