### ISSUE TITLE
No photos case

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#99]
If a user has recorded a plog without any photos, extend the map so that it extends to full width of the screen (basically filling the space taken up by pictures). 

![IMG_5222 2](https://user-images.githubusercontent.com/8822863/71017450-dcff8b80-20f6-11ea-81e2-6e29d12e71db.jpg)

**Comment by nlkassad** [comment]
an alternate temporary solution would be to have a default 'trash' image that's loaded by default.
